name: Restudy_ci

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: [3.7, 3.8]
  
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.pyhton-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version}}
      
    - name: Install Poetry
      run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    
    - name: Poetry export requirements
      run: ~/.poetry/bin/poetry export -f requirements.txt > requirements.txt
      
    - name: Install Python packages
      run: ./poetry/bin/poetry install
